### ISSUE TITLE
[Feature]: No-login way to Downloading Sentinel-1 Precise and Restituted Orbit Files

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#178]
We can simplify document https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_3.pdf because there is Python package "sentineleof" which allows downloading the both Precise and Restituted orbit files without registration via SciHub (by default). That's more easy as we don't need to manage passwords on multiple cloud processing hosts for this way. See how to install the package and download the orbits for all Sentinel-1 products in current directory:
```
pip3.7 install sentineleof
eof
```
Sure, we are able to change search and saving paths, see
```
eof --help
```

**Comment by mobigroup** [comment]
So it looks as we can completely exclude this command (for Linux, for MacOS use organize_files_tops.csh instead):
```
organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 1
```
and replace it by this one
```
eof
```
and continue by
```
organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 2
```
while it fails on restituted orbits:
```
Combing /home/jupyter/GMTSAR/asc/data/S1A_IW_SLC__1SDV_20210731T144506_20210731T144534_039023_049ABF_9E23.SAFE ...
if: Missing file name.
```
I think that's restituted orbits just missed in the code because the script calls create_frame_tops.csh inside.

**Comment by Xiaohua-Eric-Xu** [comment]
The script was written before this package came out. 
I did not quite get your second question. What did you actually do? changing all the `wgetasf` commands to `eof`?

**Comment by mobigroup** [comment]
We don’t need the alias wgetasf (which is problematic to use on some hosts) because this command can be excluded completely

organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 1

The “eof” command downloads ALL the orbits.

P.S. Imho, that’s very hard to support a complex datetime processing on shell scripts for all operating systems and architectures and any language like to perl/python/etc. is much more robust and easy to support. So “eof” work for me on macos/debian/ubuntu without any problems and without user credentials required.

**Comment by lumirinc** [comment]
@mobigroup 

I am using sentineleof library to download orbit file. Previously it was working file, however today it's giving following exception. 

[11/23 15:33:10] [INFO download.py] Downloading precise orbits for S1B on 2021-10-01
[11/23 15:33:10] [INFO download.py] Downloading precise orbits for S1B on 2021-10-13
Traceback (most recent call last):
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1012, in _check_scihub_response
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://scihub.copernicus.eu/gnss/search?format=json&rows=100&start=0&q=beginPosition%3A%5B%222021-09-30T08%3A41%3A21Z%22+TO+%222021-10-02T08%3A41%3A21Z%22%5D+platformserialidentifier%3A%221B%22+producttype%3A%22AUX_POEORB%22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gmtsar-user/.local/bin/eof", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/eof/cli.py", line 54, in cli
    download.main(
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/eof/download.py", line 384, in main
    return download_eofs(
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/eof/download.py", line 95, in download_eofs
    products = client.query_orbit(dt - ScihubGnssClient.T0,
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/eof/scihubclient.py", line 66, in query_orbit
    products = self._api.query(**query_params)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 286, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 359, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 393, in _load_subquery
    self._check_scihub_response(response, query_string=query)
  File "/home/gmtsar-user/.local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 1058, in _check_scihub_response
    raise ServerError(msg, response)
sentinelsat.exceptions.ServerError: HTTP status 503 Service Unavailable: 
# 503 Service Unavailable

No server is available to handle this request.

**Comment by mobigroup** [comment]
@lumirinc 
That works for me:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7342379/143391251-15f053bf-4d51-4fd6-ba5f-bd4a7f880f6c.png">

**Comment by lumirinc** [comment]
The day I post this issue, I guess the API was down. From the next day it's working fine.
